### ISSUE TITLE
Links do not behave like they should

### ISSUE THREAD

**Issue by max-programming** [HastePasteApp/website#3]
Links do not behave like they should, like showing the url on bottom left, and open in new tab options etc.

![image](https://user-images.githubusercontent.com/51731966/127639150-317393c2-c53f-4442-83c7-dafc216e09c7.png)

![image](https://user-images.githubusercontent.com/51731966/127639055-5e91c45b-6b51-4910-8bc6-9b97e2f8aa05.png)

**Comment by barbarbar338** [comment]
Yup because they are using next/link

**Comment by max-programming** [comment]
> Yup because they are using next/link

They should not behave like this. Take for example nextjs.org.
I have a fix for that. I will make a PR if want :)

**Comment by barbarbar338** [comment]
i will be very happy if you do :)

**Comment by max-programming** [comment]
> i will be very happy if you do :)

Thanks! Almost done. Will also add something to make it better.
